config/routes.rb
Rails.application.routes.draw do

# ルートパス
root :to =>"public/homes#about"

get "/top" => "public/homes#top"


# ユーザー用devise
# URL /users/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用devise
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

# ゲストユーザー用devise
devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/...
namespace :admin do
  root :to => "homes#top"
  resources :tea_types, only:[:index, :create, :edit, :update, :destroy]
  resources :users, only:[:show, :edit, :update]
  resources :teas, only:[:show, :index] do
   resources :tea_comments, only:[:destroy]
  end 
  
end

# ユーザー用
# URL /users/...
scope module: :public do
  # ランキング機能
  get '/teas/ranking' => "rankings#ranking"
  
  resources :users, only:[:index, :show, :edit, :update, :favorite] do
    get "/favorites" => "users#favorite"
  end
  
  resources :teas, only:[:show, :update, :edit, :destroy, :new, :create] do
    resource :favorites, only:[:create, :destroy]
    resources :tea_comments, only:[:create, :destroy]
    member do
      get :confirm
      get :new_confirm
      get :draft
    end
  end

  #検索機能
  get '/search_tea_tag', to: 'teas#search_tag'
  get '/search_tea_type', to: 'teas#search_tea_type'
  get '/search' => "searches#search"
  get '/sort_by_prefecture' => "users#sort_by_prefecture"
  

end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tea.rb
class Tea < ApplicationRecord

  belongs_to :tea_type
  belongs_to :prefecture
  belongs_to :user
  
  has_many :favorites
  has_many :tea_comments
  
  # 複数タグ投稿機能のリレーション
  has_many :tea_tags, dependent: :destroy
  has_many :tags, through: :tea_tags
  
  # いいね機能
  has_many :favorites, dependent: :destroy
  
  # コメント機能(新着順に表示)
  has_many :tea_comments, -> { order(created_at: :desc) }, dependent: :destroy
  
  has_one_attached :tea_image
  
  # enum定義 draft=下書き unpublished=非公開　published=公開
  enum status: {draft: 0, unpublished: 1, published: 2 }
  
  # 投稿画像、感想、商品名、購入場所にバリデーションを設定
  with_options presence: true, on: :published do
    validates :opinion
    validates :product_name
    validates :tea_image
    validates :purchased_at
  end
    validates :opinion, length: { maximum: 500 }

  # 画像の拡張子バリデーション追加
  validate :image_content_type, if: :was_attached?
  
  # 拡張子の確認を行う
  def image_content_type
    extension = ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'image/pjpeg', 'image/tiff', 'image/bmp', 'image/vnd.adobe.photoshop', 'image/vnd.microsoft.icon', 'image/webp']
    errors.add(:tea_image, "に利用できない拡張子が選択されています。jpg/jpeg/pngで投稿してください。") unless tea_image.content_type.in?(extension)
  end
  
  # 画像が添付されてない時は拡張子の確認をしない
  def was_attached?
    self.tea_image.attached?
  end
  
  # 画像のサイズ指定の可変化の設定
  def get_tea_image(width, height)
    unless tea_image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    tea_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpg')
    end
    tea_image.variant(resize_to_limit: [width, height]).processed
  end
   
  #複数タグを保存するためのsave_tagを定義
  def save_tag(sent_tags)
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - self.tags.pluck(:name)
    # 新しいタグを保存
    new_tags.each do |new|
      name = new.strip() # スペースを除去する
      if !name.empty? # 空白でないことを確認する
        self.tags << Tag.find_or_create_by(name: name)
      end
    end
  end
  
  # 検索窓でのサーチアクションを定義（キーワード検索）
  def self.search(search)
    # nilでない限り、商品名、投稿文の曖昧検索と産地の前方一致検索を行う
    if search != nil
      Tea.joins(:prefecture).where('product_name LIKE(?) or opinion LIKE(?) or prefectures.name LIKE(?)' , "%#{search}%",  "%#{search}%", "#{search}%")
    else
      render "public/homes/top"
    end
  end
  
  # いいね機能
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # お茶の種類絞り込み検索
  scope :tea_search, -> (search_params) do
    return if search_params.blank?
    tea_type_ids = []
    search_params.each do |name|
    tea_type_ids << TeaType.where(name: name).pluck(:id)
    end
    where(tea_type_id: tea_type_ids.flatten!)
  end

end

app/models/tea_type.rb
class TeaType < ApplicationRecord
  
  has_many :teas

  # お茶の種類名のバリデーション
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/teas_controller.rb
class Admin::TeasController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @teas = Tea.where(status: "published").page(params[:page]).per(10).order('created_at DESC')
  end
  
  def show
    @tea = Tea.find(params[:id])
    
    if @tea.status != "published"
      redirect_to admin_root_path
    end
    
    @tea_tags = @tea.tags
    @user = @tea.user
    
    # 参加して何日経ったのかを’ハンター歴’として表示するための日付計算       
    @d1 = Date.today
    @d2 = (@user.created_at).to_date
    # 今日の日付と参加日の差分を計算し文字列で取得    
    @hunter_histroy = (@d1 - @d2).to_i
  end
end

app/helpers/admin/teas_helper.rb
module Admin::TeasHelper
end

app/views/admin/teas/_teas.html.erb
<table class= "table table-hover table-inverse text-nowrap">
  <thead>
    <tr>
      <th>投稿ID</th>
      <th>投稿日</th>
      <th>投稿画像</th>
      <th>投稿者</th>
      <th>投稿文</th>
      <th>お気に入り数</th>
      <th>コメント数</th>
    </tr>
  </thead>
  <tbody>
    <% teas.each do |tea| %>
    <tr>
      <td class="text-center">
        <%= tea.id %>
      </td>
      <td>
        <%= tea.created_at.strftime('%Y/%m/%d') %>
      </td>
      <td>
        <%= link_to admin_tea_path(tea) do %>
        <%= image_tag tea.get_tea_image(50,50),class: "img-print-draft" %>
        <% end %>
      </td>
      <td>
        <%= link_to admin_user_path(tea.user), class: "link-dark" do %>
        <%= tea.user.name %>
        <% end %>
      </td>
      <td>          
        <%= link_to admin_tea_path(tea), class: "link-dark" do %>
        <%= tea.opinion.truncate(15) %>
        <% end %>
      </td>
      <td class="text-center">
        <%= tea.favorites.count %>
      </td>
      <td class="text-center">
        <%= tea.tea_comments.count %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/teas/index.html.erb
<div class="container">
  <div class="row">
    <h5 class="text-center mb-5">投稿一覧</h5>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-10 table-responsive-md">
      <%= render 'admin/teas/teas', teas: @teas %>
    </div>
  </div>
  
  <div class="row"> 
    <div class="d-flex justify-content-center mb-5">
      <% if @teas %>
      <%= paginate @teas, theme: 'bootstrap-5' %>
      <% end %>
    </div>
  </div> 

</div>

app/views/admin/teas/show.html.erb
<div class="container">
  <div class="row justify-content-center">
   
    <h4 class="text-center mb-5">投稿詳細</h4>  
      
    <div class="col-lg-3 col-8">
      <%= render "admin/users/info", user: @user %>
    </div>
  
    <div class="col-lg-8">
      <div class="row justify-content-center" >
        <div class="col-md-5 col-10">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <td><%= image_tag @tea.get_tea_image(300,350), class: "tea-image-w" %></td>
              </tr>
              <tr>
                <td><%= @tea.created_at.strftime('%Y/%m/%d') %></td>
              </tr>
            </tbody>
          </table>
        </div>
    
        <div class="col-10 col-md-5 table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td>お茶の種類</td>
                <td><%= @tea.tea_type.name %></td>
              </tr>
              <tr>
                <td>産地</td>
                <td><%= @tea.prefecture.name %></td>
              </tr>
              <tr>
                <td>商品名</td>
                <td><%= @tea.product_name %></td>
              </tr>
              <tr>
                <td>販売者</td>
                <td><%= @tea.seller %></td>
              </tr>
              <tr>
                <td>購入場所</td>
                <td><%= @tea.purchased_at %></td>
              </tr>
              <tr>
                <td>#タグ</td>
                <td>
                  <% @tea_tags.each do |tag| %>
                    <%= "#" %><%= tag.name %>
                    <%= "" %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
    
        <div class="col-10"> 
        <%= @tea.opinion %>
        </div>
      </div>
    </div>
  </div>
    
  <div class="row justify-content-center">
    
    <div class="col-8">
      <div class="row">
        <div class="col-10">
        <%= form_with model: @tea_comment, url: tea_tea_comments_path(@tea.id), local: false do |form| %>
          <%= form.text_field :comment, rows: "5" ,class: 'form-control', :placeholder => "管理者はコメントできません。"  %>
        </div>
        <div class="col-10 col-xl-2">
          <%= form.submit 'コメントする' , class: 'btn btn-primary mt-1', id: "submit", disabled: true %>
        </div>
        <% end %>
      </div>
      
      <div id="tea_comment-<%= @tea.id %>" class="table-responsive" >
        <%= render 'public/tea_comments/tea_comment', tea_comment: @tea_comment, tea: @tea %>
      </div>
    </div>
    
  </div>
  
</div>