config/routes.rb
Rails.application.routes.draw do

# ルートパス
root :to =>"public/homes#about"

get "/top" => "public/homes#top"


# ユーザー用devise
# URL /users/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用devise
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

# ゲストユーザー用devise
devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/...
namespace :admin do
  root :to => "homes#top"
  resources :tea_types, only:[:index, :create, :edit, :update, :destroy]
  resources :users, only:[:show, :edit, :update]
  resources :teas, only:[:show, :index] do
   resources :tea_comments, only:[:destroy]
  end 
  
end

# ユーザー用
# URL /users/...
scope module: :public do
  # ランキング機能
  get '/teas/ranking' => "rankings#ranking"
  
  resources :users, only:[:index, :show, :edit, :update, :favorite] do
    get "/favorites" => "users#favorite"
  end
  
  resources :teas, only:[:show, :update, :edit, :destroy, :new, :create] do
    resource :favorites, only:[:create, :destroy]
    resources :tea_comments, only:[:create, :destroy]
    member do
      get :confirm
      get :new_confirm
      get :draft
    end
  end

  #検索機能
  get '/search_tea_tag', to: 'teas#search_tag'
  get '/search_tea_type', to: 'teas#search_tea_type'
  get '/search' => "searches#search"
  get '/sort_by_prefecture' => "users#sort_by_prefecture"
  

end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :prefecture

  has_one_attached :profile_image

  has_many :teas, dependent: :destroy
  
  # いいね機能
  has_many :favorites, dependent: :destroy
  # コメント機能
  has_many :tea_comments, dependent: :destroy

  # 名前、メールアドレス、都道府県、自己紹介にバリデーションを設定
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :email, presence: true
  validates :prefecture_id, presence: true
  validates :introduction, length: { maximum: 50 }
  
  # 画像の拡張子バリデーション追加
  validate :image_content_type, if: :was_attached?
  # 拡張子の確認を行う
  def image_content_type
    extension = ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'image/pjpeg', 'image/tiff', 'image/bmp', 'image/vnd.adobe.photoshop', 'image/vnd.microsoft.icon', 'image/webp']
    errors.add(:profile_image, "に利用できない拡張子が選択されています。jpg/jpeg/pngで投稿してください。") unless profile_image.content_type.in?(extension)
  end
  # 画像が添付されてない時は拡張子の確認をしない
  def was_attached?
    self.profile_image.attached?
  end
  
  
  
  # プロフィール画像が設定されていない場合にデフォルト画像を表示させる
  def get_profile_image(width, height)
    unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/login-image.png')
    profile_image.attach(io:File.open(file_path),filename:'login-image.png',content_type:'image/png')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # ゲストユーザーログイン用
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com', prefecture_id: 1 ) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

 # ユーザー地域絞り込み検索
  scope :user_sort, -> (sort_params) do
    return if sort_params.blank?
    prefecture_ids = []
    sort_params.each do |name|
    prefecture_ids << Prefecture.where(name: name).pluck(:id)
    end
    where(prefecture_id: prefecture_ids.flatten!)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def show
    @user = User.find(params[:id])
    @teas = @user.teas.where(status: "published").page(params[:page]).per(10).order('created_at DESC')
  end
  
  def edit
    @user = User.find(params[:id])
  
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @teas = @user.teas.where(status: "published").page(params[:page]).per(10).order('created_at DESC')
    render :show
  
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:email,:prefecture_id, :is_active)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to top_path, notice: 'ゲストユーザーでログインしました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_info.html.erb
<table border="3" sellspacing="10" class="table table-borderless table-light">
  <tbody>
    
    <tr>
      <td class="mt-2 d-flex justify-content-center"><%= image_tag user.get_profile_image(100,100) %></td>
    </tr>
    
    <tr>
      <td>
        <%= link_to admin_user_path(user), class: "link-dark" do%>
          <i class="fas fa-user me-2"></i><%= user.name %>
        <% end %>
      </td>
    </tr>
    
    <tr>
      <td><i class="fas fa-binoculars me-2"></i>ハンター歴：<%= @hunter_histroy  %>日</td>
    </tr>
    
    <tr>
      <td><i class="far fa-gem me-2"></i>集めたトレチャー：<%= user.teas.where(status: "published").count %>個</td>
    </tr>
    
    <tr>
      <td><i class="fas fa-map-pin me-3"></i><%= user.prefecture.name %>在住</td>
    </tr>
    
    <tr>
      <td><i class="far fa-comment me-1"></i><%= user.introduction %></td>
    </tr>
    
    <tr>
      <td><%= link_to "投稿一覧に戻る", admin_teas_path, class: "mb-2 btn d-grid btn-outline-dark" %></td>
    </tr>

  </tbody>
</table>

app/views/admin/users/edit.html.erb
<div class="container">
  
  <div class="row">
    <h5 class="text-center mb-5"><%= @user.name %>さんのユーザー編集画面</h5>
  </div>
  
  <%= render 'layouts/errors', obj: @user %>
  
  <div class="row d-flex justify-content-center">
    
    <div class="col-12 col-lg-7">
      
    <%= form_with model: @user, url: admin_user_path(@user) do |form| %>
    
      <div class="table-responsive">
        <table class="table table-light align-middle table-borderless text-nowrap">
          <tbody>
            <tr class="form-group">
              <td><%= "プロフィール画像" %></td>
              <td><%= image_tag @user.get_profile_image(100,100) %></td>
            </tr>
            
            <tr class="form-group">
              <td><%= "ユーザーID" %></td>
              <td><%=  @user.id %></td>
            </tr>
  
            <tr class="form-group">
              <td><%= "登録日" %></td>
              <td><%= @user.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
  
            <tr class="form-group">
              <td><%= form.label :"ユーザーネーム" %></td>
              <td><%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %></td>
            </tr>
            
            <tr class="form-group">
              <td><%= form.label :"お住まいの地域" %></td>
              <td><%= form.select :prefecture_id, Prefecture.pluck(:name, :id), class: "form-control" %></td>
            </tr>
            
            <tr class="form-group">
              <td><%= form.label :"メールアドレス" %></td>
              <td><%= form.email_field :email, autocomplete: "email", class: "form-control" %></td>
            </tr>
            
            <tr class="form-group">
              <td><%= "自己紹介" %></td>
              <td><%= @user.introduction %></td>
            </tr>

            <tr clas="form-group">
              <td><%= form.label "会員ステータス" , class: "col-sm-2 control-label"%></td>
              <td><%= form.radio_button :is_active, :true %>
                <%= form.label :is_active, "有効", value: true %>
                <%= form.radio_button :is_active,  :false %>
                <%= form.label :is_active, "停止中", value: false %>
              </td>
            </tr>
          </tbody>
          </table>
        </div>
          
      <div class="actions d-flex justify-content-evenly mb-5">
        <%= form.submit "変更を保存する", class: "btn btn-outline-success" %>
        <%= link_to admin_user_path(@user), class: "btn btn-outline-secondary" do %>
          保存せずに戻る
        <% end %> 
      </div>      
    <% end %>      
  </div>         
</div>         
     
      

app/views/admin/users/show.html.erb
<div class="container">
  
  <div class="row justify-content-center">
    <h5 class="col-3 text-center mb-4 show-title">ユーザーInfo</h5>
    <h5 class="col-8 text-center mb-4 show-title">ユーザー投稿一覧</h5>
  </div>
  <div class="row justify-content-center">
    
    <div class="col-lg-4 col-md-10 me-2 mt-3">
      <table border="3" sellspacing="10" class="table table-light">
        <tbody>
          <tr>
            <td colspan="2" class="text-center"><%= image_tag @user.get_profile_image(100,100) %></td>
          </tr>
          <tr>
            <td><%= "ユーザーID" %></td>
            <td><%=  @user.id %></td>
          </tr>
          
          <tr>
            <td><%= "登録日" %></td>
            <td><%= @user.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          
          <tr>
            <td><%= "ユーザー名" %></td>
            <td><%= @user.name %></td>
          </tr>
          
          <tr>
            <td><%= "お住まいの地域" %></td>
            <td><%= @user.prefecture.name %></td>
          </tr>
          
          <tr>
            <td><%= "メールアドレス" %></td>
            <td><%= @user.email %></td>
          </tr>
          
          <tr>
            <td><%= "自己紹介" %></td>
            <td><%= @user.introduction %></td>
          </tr>
          
          <tr>
            <td><%= "会員ステータス" %></td>
            <td><%= @user.is_active ? '有効' : '停止中' %></td>
          </tr>
          <tr>
            <td colspan="2" class="text-center"><%= link_to "情報編集する", edit_admin_user_path(@user), class: "btn btn-outline-secondary" %></td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <div class="col-lg-7 col-10 table-responsive">
      <% if @teas %> 
      <%= render "admin/teas/teas", teas: @teas %>
      <% end %>
    </div>
          
  </div>
</div>
 