config/routes.rb
Rails.application.routes.draw do

# ルートパス
root :to =>"public/homes#about"

get "/top" => "public/homes#top"


# ユーザー用devise
# URL /users/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用devise
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

# ゲストユーザー用devise
devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/...
namespace :admin do
  root :to => "homes#top"
  resources :tea_types, only:[:index, :create, :edit, :update, :destroy]
  resources :users, only:[:show, :edit, :update]
  resources :teas, only:[:show, :index] do
   resources :tea_comments, only:[:destroy]
  end 
  
end

# ユーザー用
# URL /users/...
scope module: :public do
  # ランキング機能
  get '/teas/ranking' => "rankings#ranking"
  
  resources :users, only:[:index, :show, :edit, :update, :favorite] do
    get "/favorites" => "users#favorite"
  end
  
  resources :teas, only:[:show, :update, :edit, :destroy, :new, :create] do
    resource :favorites, only:[:create, :destroy]
    resources :tea_comments, only:[:create, :destroy]
    member do
      get :confirm
      get :new_confirm
      get :draft
    end
  end

  #検索機能
  get '/search_tea_tag', to: 'teas#search_tag'
  get '/search_tea_type', to: 'teas#search_tea_type'
  get '/search' => "searches#search"
  get '/sort_by_prefecture' => "users#sort_by_prefecture"
  

end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<!--バリデーションエラーのテンプレート-->
<% if obj.errors.any? %>
<div class="row justify-content-center" >
  <div id="error_explanation" class="col-10">
    <h4>
      <%= obj.errors.count %>件のエラーが発生しました。
    </h4>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div>
    <p class="text-center">@Treacha_hunter</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header header-bg-color--extend">
  <div class="container">
    <div class="row">
      
      <nav class="col-xl-9 navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <% if admin_signed_in? %>
          <a class="navbar-brand" href="/admin"><%= image_tag 'logo.jpg', size: '100x100', class: 'ml-5 ' %></a>
          <% else %>
          <a class="navbar-brand" href="/top"><%= image_tag 'logo.jpg', size: '100x100', class: 'ml-5 ' %></a>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
            <% if admin_signed_in? %>
              <li>
                <%= link_to admin_root_path,class: 'nav-link text-dark' do %>
                <i class="fas fa-home me-1"></i>会員一覧
                <% end %>
              </li>
              <li>
                <%=  link_to admin_teas_path,class: 'nav-link text-dark' do %>
                <i class="fas fa-coffee me-1"></i>投稿一覧
                <% end %>
              </li>
              <li>
                <%=  link_to admin_tea_types_path ,class: 'nav-link text-dark' do %>
                <i class="fas fa-users me-1"></i>ジャンル一覧
                <% end %>
              </li>
              <li>
                <%=  link_to destroy_admin_session_path ,method: :delete, class: 'nav-link text-dark' do %>
                <i class="fas fa-sign-out-alt me-1"></i>ログアウト
                <% end %>
              </li>
            <% elsif user_signed_in? %>
              <li>
                <%= link_to user_path(current_user),class: 'nav-link text-dark' do %>
                <i class="fas fa-home me-1"></i>マイページ
                <% end %>
              </li>
              <li>
                <%=  link_to top_path,class: 'nav-link text-dark' do %>
                <i class="fas fa-coffee me-1"></i>投稿一覧
                <% end %>
              </li>
              <li>
                <%=  link_to users_path ,class: 'nav-link text-dark' do %>
                <i class="fas fa-users me-1"></i>トレチャーハンターたち
                <% end %>
              </li>
              <li>
               <!--絞り込み検索機能-->
                <%= render "public/teas/search_tea_type" %>
              </li>
              <li>
                <%=  link_to teas_ranking_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-star me-1"></i>人気ランキング
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path,class: 'nav-link text-dark' do %>
                  <i class="fas fa-coffee me-1"></i>About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path,class: 'nav-link text-dark' do %>
                  <i class="fas fa-user-plus me-1"></i>新規登録
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path ,class: 'nav-link text-dark' do %>
                  <i class="fas fa-sign-in-alt me-1"></i>ログイン
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
     <% if user_signed_in? %>
      <div class="col-xl-3 justify-content-center align-items-center d-flex" >
      <%= form_with url: search_path, method: :get, local: :true do |f| %>
      <%= f.text_field :keyword, placeholder: "Search"%>
      <%= f.submit "検索" %>
      <% end %>
      </div>
      <% end %>
    </div>
  </div>  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TreachaHunter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!--Bootstrap5 CSS START-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  
    <!--Bootstrap5 CSS END-->
    
    <!--jquery Start-->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!--jquery End-->
    
    <%= javascript_include_tag "script" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="body--extend">
    <%= render "layouts/header" %>
    <p id="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "layouts/footer" %>
    <!-- Bootstrap5 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>