config/routes.rb
Rails.application.routes.draw do

# ルートパス
root :to =>"public/homes#about"

get "/top" => "public/homes#top"


# ユーザー用devise
# URL /users/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用devise
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

# ゲストユーザー用devise
devise_scope :user do
  post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
end

# 管理者用
# URL /admin/...
namespace :admin do
  root :to => "homes#top"
  resources :tea_types, only:[:index, :create, :edit, :update, :destroy]
  resources :users, only:[:show, :edit, :update]
  resources :teas, only:[:show, :index] do
   resources :tea_comments, only:[:destroy]
  end 
  
end

# ユーザー用
# URL /users/...
scope module: :public do
  # ランキング機能
  get '/teas/ranking' => "rankings#ranking"
  
  resources :users, only:[:index, :show, :edit, :update, :favorite] do
    get "/favorites" => "users#favorite"
  end
  
  resources :teas, only:[:show, :update, :edit, :destroy, :new, :create] do
    resource :favorites, only:[:create, :destroy]
    resources :tea_comments, only:[:create, :destroy]
    member do
      get :confirm
      get :new_confirm
      get :draft
    end
  end

  #検索機能
  get '/search_tea_tag', to: 'teas#search_tag'
  get '/search_tea_type', to: 'teas#search_tea_type'
  get '/search' => "searches#search"
  get '/sort_by_prefecture' => "users#sort_by_prefecture"
  

end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/tea_types_controller.rb
class Admin::TeaTypesController < ApplicationController
  
  before_action :authenticate_admin!
  
  def create
    @tea_type = TeaType.new(tea_type_params)
    if @tea_type.save
      redirect_to admin_tea_types_path
    else
      @tea_types = TeaType.page(params[:page]).per(20)
      render :index
    end
  end

  def index
    @tea_type = TeaType.new
    @tea_types = TeaType.page(params[:page]).per(20)
  end

  def edit
    @tea_type = TeaType.find(params[:id])

  end

  def update
    @tea_type = TeaType.find(params[:id])
    if @tea_type.update(tea_type_params)
      redirect_to admin_tea_types_path
    else
      render :edit
    end
  end

  def destroy
    @tea_type = TeaType.find(params[:id])
    if Tea.find_by(tea_type_id: @tea_type.id).present?
      redirect_to admin_tea_types_path, notice: 'この種類名は投稿に紐づいているため削除できません'
    else
      @tea_type.destroy
      redirect_to request.referer
    end
  end

  private
    def tea_type_params
      params.require(:tea_type).permit(:name)
    end
end

app/helpers/admin/tea_types_helper.rb
module Admin::TeaTypesHelper
end

app/views/admin/tea_types/edit.html.erb
<div class="container">
  
  <div class="row">
    <h5 class="text-center mb-4">お茶の種類名編集</h5>
  </div>
  <%= render 'layouts/errors', obj: @tea_type %>
  <div class="row mb-5">
    <table>
      <%= form_with model: @tea_type, url: admin_tea_type_path(@tea_type) do |form| %>
      <tbody>
        <tr class="field">
          <td>
            <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control"%>
          </td>
        
          <td class="actions">
            <%= form.submit "変更を保存する", class: "ms-5 btn btn-outline-success" %>
            <%= link_to "変更せずに戻る", admin_tea_types_path, class: "ms-1 btn btn-outline-secondary" %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>

app/views/admin/tea_types/index.html.erb
<div class="container">
  
  <div class="row">
    <h5 class="text-center mb-4">お茶の種類一覧・登録</h5>
  </div>
  <%= render 'layouts/errors', obj: @tea_type %>
  <div class=row>
    <div class="text-center" >
      <%= form_with model: @tea_type, url: admin_tea_types_path(@tea_type) do |form| %>
      <%= form.text_field :name %>
      <%= form.submit "新規登録", class: "btn btn-outline-primary mb-3" %>
      <% end %>
    </div>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-8 table-responsive-md">
      <table class= "table table-hover table-inverse text-nowrap table-sm">
        <thead>
          <tr class="text-center">
            <th>ID</th>
            <th>種類名</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @tea_types.each do |tea_type| %>
          <tr class="text-center">
            <td>
              <%= tea_type.id %>
            </td>
            <td>
              <%= tea_type.name %>
            </td>
            <td>
              <%= link_to "編集する", edit_admin_tea_type_path(tea_type), class: "btn btn-sm btn-outline-success" %>&nbsp;
              <%= link_to "削除する", admin_tea_type_path(tea_type), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-sm btn-outline-danger" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row"> 
      <div class="d-flex justify-content-center mb-5">
        <% if @tea_types %>
        <%= paginate @tea_types, theme: 'bootstrap-5' %>
        <% end %>
      </div>
    </div> 

  </div>
</div>